# SwiftLint Configuration for ScreenshotRenamer
# Provides fast code quality and style checking on every commit

# Paths to include in linting
included:
  - Sources
  - Tests

# Paths to exclude
excluded:
  - .build
  - .swiftpm
  - Scripts
  - Packages
  - Package.resolved

# Disable rules that conflict with project style
disabled_rules:
  - trailing_whitespace  # Allow trailing whitespace in comments for alignment
  - inclusive_language   # "whitelist" is security terminology, not referring to race
  - file_header         # Files have varying header styles, not critical for small project
  - blanket_disable_command  # Allow blanket disables in small project for simplicity

# Opt-in to additional rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Customize rule parameters
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k
    - db
    - URL
    - GlobalAPIKey

nesting:
  type_level:
    warning: 2

# Custom rules
custom_rules:
  no_nslog:
    name: "No NSLog"
    regex: '\bNSLog\('
    message: "Use os_log instead of NSLog"
    severity: error

reporter: "xcode" # Use Xcode-style reporting format
